BookBazaar/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from baseapp import views
app_name = 'baseapp'
urlpatterns = [
    path("admin/", admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path("", views.home_view, name = 'home'),
    path('home/', views.afterlogin_home_view, name = 'afterlogin_home'),
    # path("login/", views.CustomLoginView.as_view(), name='custom_login'),
    path("about/", views.about_view, name = 'about'),
    path("contact/", views.contact_view, name = 'contact'),
    path("buy/", views.buy_view, name = 'buy'),
    path("sell/", views.book_add_view, name = 'sell'),
    # path("accounts/", include('django.contrib.auth.urls'), name = 'login'),
    # path("accounts/profile/", views.dashboard_view, name = 'profile')
    
    path("sell-list/", views.sale_list_view, name = 'sale-list'),
    path("books/", views.book_list_view, name = 'book_list'),
    path("<slug:category_slug>/", views.book_list_view, name = 'book_list_by_category'),
    path("<int:id>/<slug:slug>/", views.book_detail, name = 'book_detail'),
    
    path("sale/<slug:category_slug>/", views.sale_list_view, name = 'sale-book_list_by_category'),
    path("sale/<int:id>/<slug:slug>/", views.sale_book_detail, name = 'sale_book_detail'),
    path("sale/update/<int:id>/<slug:slug>/", views.sale_update_view, name = "sale_update"),
    path("accounts/login/", auth_views.LoginView.as_view(template_name = 'baseapp/home.html'), name = 'login'),
    
    path("accounts/logout/", auth_views.LogoutView.as_view(next_page = '/'), name = 'logout'),
    path("accounts/profile/", login_required(views.UserView.as_view()), name = 'profile'),
    path("accounts/signup/", views.signup, name = 'signup'),
    
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT,
    )

cart/urls.py
from django.urls import path
from . import views
app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name = 'cart_detail'),
    path('add/<int:book_id>/', views.cart_add, name = 'cart_add'),
    path('remove/<int:book_id>/', views.cart_remove, name = 'cart_remove'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms 
BOOK_QUANTITY_CHOICES = [(i, str(i)) for i in range(0, 2)]
class CartAddBookForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices = BOOK_QUANTITY_CHOICES,
        coerce = int
    )
    override = forms.BooleanField(
        required = False,
        initial = False,
        widget = forms.HiddenInput
    )

cart/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_POST
from baseapp.models import Book
from .cart import Cart
from .forms import CartAddBookForm
# Create your views here.
@require_POST
def cart_add(request, book_id):
    cart = Cart(request)
    book = get_object_or_404(Book, id = book_id)
    form = CartAddBookForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(book = book, quantity=cd['quantity'], override_quantity=cd['override'])
    return redirect('cart:cart_detail')

@require_POST
def cart_remove(request, book_id):
    cart = Cart(request)
    book = get_object_or_404(Book, id = book_id)
    cart.remove(book)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddBookForm(initial={'quantity':item['quantity'], 'override':True})
    return render(request, 'cart/detail.html', {'cart':cart})

templates/cart/detail.html
{% extends "baseapp/afterlogin_base.html" %}
{% load static %}
{% block title %}BookBazaar | Cart {% endblock title %}
{% block css %}<link rel="stylesheet" href={% static 'css/cart_detail.css' %} />{% endblock css %}
{% block body %}
<main>
   <h1>Your shopping cart</h1>
   <div class="cart">
      {% for item in cart %} 
         {% with book=item.book %} 
         <div class="cartItems">
            
            <div class="image">
               <a href="{{ book.get_absolute_url }}">
               <img src="{% if book.image %}{{ book.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
               </a>
            </div>
            <div class="product">
               {{ book.name }}
            </div>
            <div class="info">
               <div class="quantity">
                  <span>Quantity:</span>
                  <form action="{%url "cart:cart_add" book.id%}" method="post">
                     {{item.update_quantity_form.quantity}}
                     {{item.update_quantity_form.override}}
                     {% csrf_token %}
                     <input type="submit" value="Update">
                  </form>
               </div>
               <div class="unitPrice">
                  <span>Unit Price:</span>
                  Rs.{{ item.price }}
               </div>
               <div class="price">
                  <span>Price:</span>
                  Rs.{{ item.total_price }}
               </div>
            </div>
            <button class = 'remove'>
               <form action="{% url "cart:cart_remove" book.id %}" method="post">
               {% csrf_token %} 
               <input type="submit" value="Remove"> 
                     
               </form>
            </button>
         </div>
         {% endwith %} 
      {% endfor %} 
      <div class="total">
         Total: Rs.{{ cart.get_total_price }}
      </div>
      <p class="text-right">
         <a href="{% url "book_list" %}" class="button light">Continue shopping</a>
         <a href="#" class="button">Checkout</a>
      </p>
   </div>




</main>
    
 
{% endblock body %}